# SHELL (FISH)
# ==============================================================================
set-option -g default-shell /usr/bin/fish

# PREFIX KEYBIND (CTRL + A)
# ==============================================================================
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# WINDOW KEYBINDS
# ==============================================================================
# CREATE NEW WINDOW (C)
bind c new-window 

# RENAME WINDOW (W)
bind w command-prompt "rename-window %%"

# NEXT & PREVIOUS WINDOWS (N/P)
bind n next-window
bind p previous-window

# PANE KEYBINDS
# ==============================================================================
# SPLIT PANES (V/H)
bind V split-window -h
bind H split-window -v

# NAVIGATE PANES (VIM MOTIONS)
bind -r j select-pane -D  # Move down
bind -r k select-pane -U  # Move up
bind -r h select-pane -L  # Move left
bind -r l select-pane -R  # Move right

# SYNC PANES (Y)
bind y setw synchronize-panes

# TMUX PLUGINS
# ==============================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

set -g status-position top
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icons session
set -g @dracula-plugins "cpu-usage gpu-usage ram-usage"
set -g @dracula-refresh-rate 2

# KEEP AT BOTTOM!
run '~/.tmux/plugins/tpm/tpm'
